config/routes.rb
Rails.application.routes.draw do
  # resources :blogs 
  root 'users#new'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :favorites, only: [:create, :destroy]
  resources :blogs do
    collection do
      post :confirm
    end
  end
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end 
  get "users/user_favorites/:id" => "users#user_favorites", as: 'user_favorites'
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  belongs_to :user
  has_many :favorites, dependent: :destroy
  has_many :favorite_users, through: :favorites, source: :user
  mount_uploader :image, ImageUploader
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }
  has_many :blogs
  has_many :favorites, dependent: :destroy
  mount_uploader :image, ImageUploader            
end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :ensure_correct_user, {only: [:edit, :update]}

  def index
    @blogs = Blog.all
  end

  def new
    @blog = current_user.blogs.build
  end

  def confirm
    # @blog = Blog.new(blog_params)
    @blog = current_user.blogs.build(blog_params)
    render :new if @blog.invalid?
  end

  def create
    # @blog = Blog.new(blog_params)
    @blog = current_user.blogs.build(blog_params)
    if params[:back]
      render :new
    elsif @blog.save
      # BlogMailer.blog_mail(@blog).deliver
      redirect_to blogs_path, notice: "投稿しました！"
    else
      render :new
    end
  end

  def show
    # @blog = Blog.find(params[:id]) 
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
    @blog = Blog.find(params[:id]) 
  end

  def update
    @blog = Blog.find(params[:id]) 
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "投稿を編集しました！"
    else
      render :edit
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"投稿を削除しました！"
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image, :image_cache)
  end
  def set_blog
    @blog = Blog.find(params[:id])
  end
  def ensure_correct_user
    if current_user.id != @blog.user.id
      flash[:notice] = "編集権限がありません"
      redirect_to blogs_path
    end
  end
  end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end
  def destroy
    favorite = current_user.favorites.find_by(id: params[:id]).destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_correct_user, {only: [:show, :edit, :update]}

  def new
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to new_session_path
    else
      render :new
    end
  end
  def show
    @user = User.find(params[:id])
  end
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id]) 
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "投稿を編集しました！"
    else
      render :edit
    end
  end
  def user_favorites
    @user = User.find(params[:id])
    @blog = Blog.where(user_id: @user.id)
  end
  private
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :image_cache)
  end
  def ensure_correct_user
    @user = User.find(params[:id])
    if current_user.id != @user.id
      flash[:notice] = "編集権限がありません"
      redirect_to blogs_path
    end
  end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'create'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    current_user.present?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true ,url: choose_new_or_edit ) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  <%= form.submit %>
<% end %>
<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>
<%= form_with(model: @blog, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= image_tag(@blog.image.url) if @blog.image && @blog.image.url %>
  <%= form.hidden_field :image_cache %>
  <%= form.submit "投稿する" %>
<% end %>

app/views/blogs/edit.html.erb
<h2>投稿編集</h2>
  <%= render 'form' %>

app/views/blogs/index.html.erb
<h1>投稿一覧</h1>
<p><%= notice %></p>
<table>
<table>
  <tr>
    <th>ユーザー名</th>
    <th>タイトル</th>
    <th>内容</th>
  </tr>
<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.user.name %></td>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <% if blog.image? %>
    <td><%= image_tag blog.image.url %></td>
    <% end %>
    <td><%= link_to '詳細確認', blog_path(blog.id) %></td>
    <% if blog.user_id == current_user.id %>
    <td><%= link_to "投稿編集", edit_blog_path(blog.id), data: { confirm: '本当に編集していいですか？' } %></td>
    <td><%= link_to '投稿削除', blog_path(blog.id), method: :delete ,data: { confirm: '本当に削除していいですか？' } %></td>
    <% end %>
  </tr>
<% end %>
</table>
<%= link_to '新しく投稿する', new_blog_path %>

app/views/blogs/new.html.erb
<h2>新規投稿</h2>
  <%= render 'form' %>

app/views/blogs/show.html.erb
<h1>投稿詳細画面</h1>
<% if @blog.image? %>
<p><%= image_tag @blog.image.url %></p>
<% end %>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<% unless @blog.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(id: @favorite.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-primary' %>
  <% end %>
<% end %>
<%= link_to "投稿一覧画面にもどる", blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SessionLogin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header>
  <h1>Miyastagram</h1>
  </header>
    <% flash.each do |key, value| %>
      <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
    <% if logged_in? %>
      <%= link_to "プロフィール", user_path(current_user.id) %>
      <%= link_to "ログアウト", session_path(current_user.id), method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_path %>
      <%= link_to "Login", new_session_path %>
    <% end %>
    <main></main>
    <%= yield %>
    <footer></footer>
  </body>
</html>

app/views/users/edit.html.erb
<%= form_with(model: @user, local: true) do |form| %>
  <div class="field">
  <%= form.label :image %>
  <%= image_tag(@user.image.url) if @user.image && @user.image.url %>
  <%= form.file_field :image %>
  <%= form.hidden_field :image_cache %>
  </div>
  <div class="blog_content">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <%= form.label :password %>
  <%= form.password_field :password %>
  <%= form.label :password_confirmation %>
  <%= form.password_field :password_confirmation %>
  <%= form.submit %>
<% end %>
<%= link_to '投稿一覧画面に戻る', blogs_path %> 

app/views/users/new.html.erb
<h1>Sign up</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this <%= @user.name %> from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>  
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.email_field :email %>
  <%= f.label :password %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.image_tag(@user.image.url) if @user.image && @user.image.url %>
  <%= f.file_field :image %>
  <%= f.hidden_field :image_cache %>
  <%= f.submit "Create my account" %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %>のページ</h1>
<p>メールアドレス: <%= @user.email %></p>
<% if @user.image? %>
  <div><%= image_tag @user.image.url %></div>
<% end %>
<%= link_to '新しく投稿する', new_blog_path %>
<%= link_to "投稿一覧画面にもどる", blogs_path %>
<%= link_to "お気に入り一覧",  user_favorites_path(@user) %> 
<% if @user == current_user %>
  <%= link_to "ユーザー情報の編集をする",  edit_user_path(@user) %> 
<% end %>

app/views/users/user_favorites.html.erb
<h3>お気に入り一覧</h3>
<table>
  <thead>
      <tr>
        <th>名前</th>
        <th>写真</th>
        <th>投稿</th>
      </tr>
  </thead>
  <tbody>
    <% @user.favorites.each do |favorite| %>
      <tr>
        <td><%= favorite.user.name %></td>
        <% if favorite.blog.image? %>
        <td><%= image_tag favorite.blog.image.url %></td>
        <% end %>
        <td><%= favorite.blog.title %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '投稿一覧画面に戻る', blogs_path %> 